name: Run unit tests on merge to Dev branch
on:
    push:
        branches:
            - dev
            - main
    pull_request:
        branches:
            - dev

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Set up dotnet
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '9.x'

            - name: Restore dependencies
              run: dotnet restore

            - name: Run unit test
              run: dotnet test
